<?php
// Bills and coins pics from: https://en.wikipedia.org/wiki/Argentine_peso#Banknotes
return ['Bills' => [
    'M10' => [
        'name' => '10 cent',
        'image' => 'ars/moneda-10c.jpg',
        'ratio' => 0.1,
        'lowLevel' => null,
        'highLevel' => 10,
    ],
    'M25' => [
        'name' => '25 cent',
        'image' => 'ars/moneda-25c.jpg',
        'ratio' => 0.25,
        'lowLevel' => null,
        'highLevel' => 30,
    ],
    'M50' => [
        'name' => '50 cent',
        'image' => 'ars/moneda-50c.jpg',
        'ratio' => 0.5,
        'lowLevel' => 10,
        'highLevel' => 50,
    ],
    'M1' => [
        'name' => '$1 mon.',
        'image' => 'ars/moneda-1.jpg',
        'ratio' => 1,
        'lowLevel' => 10,
        'highLevel' => 50,
    ],
    'M2' => [
        'name' => '$2 mon.',
        'image' => 'ars/moneda-2.jpg',
        'ratio' => 2,
        'lowLevel' => null,
        'highLevel' => 20,
    ],
    'B2' => [
        'name' => '$2',
        'image' => 'ars/billete-2.png',
        'ratio' => 2,
        'lowLevel' => 10,
        'highLevel' => 40,
    ],
    'B5' => [
        'name' => '$5',
        'image' => 'ars/billete-5.png',
        'ratio' => 5,
        'lowLevel' => 10,
        'highLevel' => 40,
    ],
    'B10' => [
        'name' => '$10',
        'image' => 'ars/billete-10.png',
        'ratio' => 10,
        'lowLevel' => 10,
        'highLevel' => 50,
    ],
    'B20' => [
        'name' => '$20',
        'image' => 'ars/billete-20.png',
        'ratio' => 20,
        'lowLevel' => 5,
        'highLevel' => 20,
    ],
    'B50' => [
        'name' => '$50',
        'image' => 'ars/billete-50.png',
        'ratio' => 50,
        'lowLevel' => 4,
        'highLevel' => 10,
    ],
    'B100' => [
        'name' => '$100',
        'image' => 'ars/billete-100.png',
        'ratio' => 100,
        'lowLevel' => null,
        'highLevel' => 10,
    ],
    'B200' => [
        'name' => '$200',
        'image' => 'ars/billete-200.png',
        'ratio' => 200,
        'lowLevel' => null,
        'highLevel' => null,
    ],
    'B500' => [
        'name' => '$500',
        'image' => 'ars/billete-500.png',
        'ratio' => 500,
        'lowLevel' => null,
        'highLevel' => null,
    ],
]];
