<?php
return ['ChangePackages' => [
    'A025' => [
        'name' => 'A|25 cent',
        'image' => 'ars/change_A025.png',
        'ratio' => 7.5,
        'lowLevel' => null,
        'highLevel' => null,
    ],
    'B050' => [
        'name' => 'B|50 cent',
        'image' => 'ars/change_B050.png',
        'ratio' => 15,
        'lowLevel' => 1,
        'highLevel' => 4,
    ],
    'C1' => [
        'name' => 'C|$1 mon.',
        'image' => 'ars/change_C1.png',
        'ratio' => 30,
        'lowLevel' => 2,
        'highLevel' => 5,
    ],
    'D2' => [
        'name' => 'D|$2 mon.',
        'image' => 'ars/change_D2.png',
        'ratio' => 40,
        'lowLevel' => null,
        'highLevel' => 4,
    ],
    'E2' => [
        'name' => 'E|$2',
        'image' => 'ars/change_E2.png',
        'ratio' => 40,
        'lowLevel' => 2,
        'highLevel' => 5,
    ],
    'F5' => [
        'name' => 'F|$5',
        'image' => 'ars/change_F5.png',
        'ratio' => 100,
        'lowLevel' => 2,
        'highLevel' => 5,
    ],
    'G10' => [
        'name' => 'G|$10',
        'image' => 'ars/change_G10.png',
        'ratio' => 300,
        'lowLevel' => 3,
        'highLevel' => 8,
    ],
    'H20' => [
        'name' => 'H|$20',
        'image' => 'ars/change_H20.png',
        'ratio' => 100,
        'lowLevel' => 2,
        'highLevel' => 8,
    ],
    'I50' => [
        'name' => 'I|$50',
        'image' => 'ars/change_I50.png',
        'ratio' => 250,
        'lowLevel' => 2,
        'highLevel' => 8,
    ],
]];
